// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer.proto

package com.aljumaro.test.proto;

public final class CustomerProtos {
  private CustomerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CustomerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aljumaro.test.proto.Customer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string email = 3;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();
  }
  /**
   * Protobuf type {@code com.aljumaro.test.proto.Customer}
   */
  public  static final class Customer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aljumaro.test.proto.Customer)
      CustomerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customer.newBuilder() to construct.
    private Customer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customer() {
      id_ = 0L;
      name_ = "";
      email_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Customer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aljumaro.test.proto.CustomerProtos.internal_static_com_aljumaro_test_proto_Customer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aljumaro.test.proto.CustomerProtos.internal_static_com_aljumaro_test_proto_Customer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aljumaro.test.proto.CustomerProtos.Customer.class, com.aljumaro.test.proto.CustomerProtos.Customer.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aljumaro.test.proto.CustomerProtos.Customer)) {
        return super.equals(obj);
      }
      com.aljumaro.test.proto.CustomerProtos.Customer other = (com.aljumaro.test.proto.CustomerProtos.Customer) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aljumaro.test.proto.CustomerProtos.Customer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aljumaro.test.proto.CustomerProtos.Customer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aljumaro.test.proto.Customer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aljumaro.test.proto.Customer)
        com.aljumaro.test.proto.CustomerProtos.CustomerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aljumaro.test.proto.CustomerProtos.internal_static_com_aljumaro_test_proto_Customer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aljumaro.test.proto.CustomerProtos.internal_static_com_aljumaro_test_proto_Customer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aljumaro.test.proto.CustomerProtos.Customer.class, com.aljumaro.test.proto.CustomerProtos.Customer.Builder.class);
      }

      // Construct using com.aljumaro.test.proto.CustomerProtos.Customer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        email_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aljumaro.test.proto.CustomerProtos.internal_static_com_aljumaro_test_proto_Customer_descriptor;
      }

      public com.aljumaro.test.proto.CustomerProtos.Customer getDefaultInstanceForType() {
        return com.aljumaro.test.proto.CustomerProtos.Customer.getDefaultInstance();
      }

      public com.aljumaro.test.proto.CustomerProtos.Customer build() {
        com.aljumaro.test.proto.CustomerProtos.Customer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aljumaro.test.proto.CustomerProtos.Customer buildPartial() {
        com.aljumaro.test.proto.CustomerProtos.Customer result = new com.aljumaro.test.proto.CustomerProtos.Customer(this);
        result.id_ = id_;
        result.name_ = name_;
        result.email_ = email_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aljumaro.test.proto.CustomerProtos.Customer) {
          return mergeFrom((com.aljumaro.test.proto.CustomerProtos.Customer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aljumaro.test.proto.CustomerProtos.Customer other) {
        if (other == com.aljumaro.test.proto.CustomerProtos.Customer.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aljumaro.test.proto.CustomerProtos.Customer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aljumaro.test.proto.CustomerProtos.Customer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.aljumaro.test.proto.Customer)
    }

    // @@protoc_insertion_point(class_scope:com.aljumaro.test.proto.Customer)
    private static final com.aljumaro.test.proto.CustomerProtos.Customer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aljumaro.test.proto.CustomerProtos.Customer();
    }

    public static com.aljumaro.test.proto.CustomerProtos.Customer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customer>
        PARSER = new com.google.protobuf.AbstractParser<Customer>() {
      public Customer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Customer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Customer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customer> getParserForType() {
      return PARSER;
    }

    public com.aljumaro.test.proto.CustomerProtos.Customer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CustomersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.aljumaro.test.proto.Customers)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
     */
    java.util.List<com.aljumaro.test.proto.CustomerProtos.Customer> 
        getCustomerList();
    /**
     * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
     */
    com.aljumaro.test.proto.CustomerProtos.Customer getCustomer(int index);
    /**
     * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
     */
    int getCustomerCount();
    /**
     * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
     */
    java.util.List<? extends com.aljumaro.test.proto.CustomerProtos.CustomerOrBuilder> 
        getCustomerOrBuilderList();
    /**
     * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
     */
    com.aljumaro.test.proto.CustomerProtos.CustomerOrBuilder getCustomerOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.aljumaro.test.proto.Customers}
   */
  public  static final class Customers extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.aljumaro.test.proto.Customers)
      CustomersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Customers.newBuilder() to construct.
    private Customers(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Customers() {
      customer_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Customers(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                customer_ = new java.util.ArrayList<com.aljumaro.test.proto.CustomerProtos.Customer>();
                mutable_bitField0_ |= 0x00000001;
              }
              customer_.add(
                  input.readMessage(com.aljumaro.test.proto.CustomerProtos.Customer.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          customer_ = java.util.Collections.unmodifiableList(customer_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aljumaro.test.proto.CustomerProtos.internal_static_com_aljumaro_test_proto_Customers_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aljumaro.test.proto.CustomerProtos.internal_static_com_aljumaro_test_proto_Customers_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aljumaro.test.proto.CustomerProtos.Customers.class, com.aljumaro.test.proto.CustomerProtos.Customers.Builder.class);
    }

    public static final int CUSTOMER_FIELD_NUMBER = 1;
    private java.util.List<com.aljumaro.test.proto.CustomerProtos.Customer> customer_;
    /**
     * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
     */
    public java.util.List<com.aljumaro.test.proto.CustomerProtos.Customer> getCustomerList() {
      return customer_;
    }
    /**
     * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
     */
    public java.util.List<? extends com.aljumaro.test.proto.CustomerProtos.CustomerOrBuilder> 
        getCustomerOrBuilderList() {
      return customer_;
    }
    /**
     * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
     */
    public int getCustomerCount() {
      return customer_.size();
    }
    /**
     * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
     */
    public com.aljumaro.test.proto.CustomerProtos.Customer getCustomer(int index) {
      return customer_.get(index);
    }
    /**
     * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
     */
    public com.aljumaro.test.proto.CustomerProtos.CustomerOrBuilder getCustomerOrBuilder(
        int index) {
      return customer_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < customer_.size(); i++) {
        output.writeMessage(1, customer_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < customer_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, customer_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.aljumaro.test.proto.CustomerProtos.Customers)) {
        return super.equals(obj);
      }
      com.aljumaro.test.proto.CustomerProtos.Customers other = (com.aljumaro.test.proto.CustomerProtos.Customers) obj;

      boolean result = true;
      result = result && getCustomerList()
          .equals(other.getCustomerList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCustomerCount() > 0) {
        hash = (37 * hash) + CUSTOMER_FIELD_NUMBER;
        hash = (53 * hash) + getCustomerList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.aljumaro.test.proto.CustomerProtos.Customers parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customers parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customers parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customers parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customers parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customers parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customers parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customers parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customers parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customers parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customers parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.aljumaro.test.proto.CustomerProtos.Customers parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.aljumaro.test.proto.CustomerProtos.Customers prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.aljumaro.test.proto.Customers}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.aljumaro.test.proto.Customers)
        com.aljumaro.test.proto.CustomerProtos.CustomersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aljumaro.test.proto.CustomerProtos.internal_static_com_aljumaro_test_proto_Customers_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aljumaro.test.proto.CustomerProtos.internal_static_com_aljumaro_test_proto_Customers_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aljumaro.test.proto.CustomerProtos.Customers.class, com.aljumaro.test.proto.CustomerProtos.Customers.Builder.class);
      }

      // Construct using com.aljumaro.test.proto.CustomerProtos.Customers.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCustomerFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (customerBuilder_ == null) {
          customer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          customerBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aljumaro.test.proto.CustomerProtos.internal_static_com_aljumaro_test_proto_Customers_descriptor;
      }

      public com.aljumaro.test.proto.CustomerProtos.Customers getDefaultInstanceForType() {
        return com.aljumaro.test.proto.CustomerProtos.Customers.getDefaultInstance();
      }

      public com.aljumaro.test.proto.CustomerProtos.Customers build() {
        com.aljumaro.test.proto.CustomerProtos.Customers result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aljumaro.test.proto.CustomerProtos.Customers buildPartial() {
        com.aljumaro.test.proto.CustomerProtos.Customers result = new com.aljumaro.test.proto.CustomerProtos.Customers(this);
        int from_bitField0_ = bitField0_;
        if (customerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            customer_ = java.util.Collections.unmodifiableList(customer_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.customer_ = customer_;
        } else {
          result.customer_ = customerBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aljumaro.test.proto.CustomerProtos.Customers) {
          return mergeFrom((com.aljumaro.test.proto.CustomerProtos.Customers)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aljumaro.test.proto.CustomerProtos.Customers other) {
        if (other == com.aljumaro.test.proto.CustomerProtos.Customers.getDefaultInstance()) return this;
        if (customerBuilder_ == null) {
          if (!other.customer_.isEmpty()) {
            if (customer_.isEmpty()) {
              customer_ = other.customer_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCustomerIsMutable();
              customer_.addAll(other.customer_);
            }
            onChanged();
          }
        } else {
          if (!other.customer_.isEmpty()) {
            if (customerBuilder_.isEmpty()) {
              customerBuilder_.dispose();
              customerBuilder_ = null;
              customer_ = other.customer_;
              bitField0_ = (bitField0_ & ~0x00000001);
              customerBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCustomerFieldBuilder() : null;
            } else {
              customerBuilder_.addAllMessages(other.customer_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aljumaro.test.proto.CustomerProtos.Customers parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aljumaro.test.proto.CustomerProtos.Customers) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.aljumaro.test.proto.CustomerProtos.Customer> customer_ =
        java.util.Collections.emptyList();
      private void ensureCustomerIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          customer_ = new java.util.ArrayList<com.aljumaro.test.proto.CustomerProtos.Customer>(customer_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.aljumaro.test.proto.CustomerProtos.Customer, com.aljumaro.test.proto.CustomerProtos.Customer.Builder, com.aljumaro.test.proto.CustomerProtos.CustomerOrBuilder> customerBuilder_;

      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public java.util.List<com.aljumaro.test.proto.CustomerProtos.Customer> getCustomerList() {
        if (customerBuilder_ == null) {
          return java.util.Collections.unmodifiableList(customer_);
        } else {
          return customerBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public int getCustomerCount() {
        if (customerBuilder_ == null) {
          return customer_.size();
        } else {
          return customerBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public com.aljumaro.test.proto.CustomerProtos.Customer getCustomer(int index) {
        if (customerBuilder_ == null) {
          return customer_.get(index);
        } else {
          return customerBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public Builder setCustomer(
          int index, com.aljumaro.test.proto.CustomerProtos.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.set(index, value);
          onChanged();
        } else {
          customerBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public Builder setCustomer(
          int index, com.aljumaro.test.proto.CustomerProtos.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.set(index, builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public Builder addCustomer(com.aljumaro.test.proto.CustomerProtos.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.add(value);
          onChanged();
        } else {
          customerBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public Builder addCustomer(
          int index, com.aljumaro.test.proto.CustomerProtos.Customer value) {
        if (customerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCustomerIsMutable();
          customer_.add(index, value);
          onChanged();
        } else {
          customerBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public Builder addCustomer(
          com.aljumaro.test.proto.CustomerProtos.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.add(builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public Builder addCustomer(
          int index, com.aljumaro.test.proto.CustomerProtos.Customer.Builder builderForValue) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.add(index, builderForValue.build());
          onChanged();
        } else {
          customerBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public Builder addAllCustomer(
          java.lang.Iterable<? extends com.aljumaro.test.proto.CustomerProtos.Customer> values) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, customer_);
          onChanged();
        } else {
          customerBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public Builder clearCustomer() {
        if (customerBuilder_ == null) {
          customer_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          customerBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public Builder removeCustomer(int index) {
        if (customerBuilder_ == null) {
          ensureCustomerIsMutable();
          customer_.remove(index);
          onChanged();
        } else {
          customerBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public com.aljumaro.test.proto.CustomerProtos.Customer.Builder getCustomerBuilder(
          int index) {
        return getCustomerFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public com.aljumaro.test.proto.CustomerProtos.CustomerOrBuilder getCustomerOrBuilder(
          int index) {
        if (customerBuilder_ == null) {
          return customer_.get(index);  } else {
          return customerBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public java.util.List<? extends com.aljumaro.test.proto.CustomerProtos.CustomerOrBuilder> 
           getCustomerOrBuilderList() {
        if (customerBuilder_ != null) {
          return customerBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(customer_);
        }
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public com.aljumaro.test.proto.CustomerProtos.Customer.Builder addCustomerBuilder() {
        return getCustomerFieldBuilder().addBuilder(
            com.aljumaro.test.proto.CustomerProtos.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public com.aljumaro.test.proto.CustomerProtos.Customer.Builder addCustomerBuilder(
          int index) {
        return getCustomerFieldBuilder().addBuilder(
            index, com.aljumaro.test.proto.CustomerProtos.Customer.getDefaultInstance());
      }
      /**
       * <code>repeated .com.aljumaro.test.proto.Customer customer = 1;</code>
       */
      public java.util.List<com.aljumaro.test.proto.CustomerProtos.Customer.Builder> 
           getCustomerBuilderList() {
        return getCustomerFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.aljumaro.test.proto.CustomerProtos.Customer, com.aljumaro.test.proto.CustomerProtos.Customer.Builder, com.aljumaro.test.proto.CustomerProtos.CustomerOrBuilder> 
          getCustomerFieldBuilder() {
        if (customerBuilder_ == null) {
          customerBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.aljumaro.test.proto.CustomerProtos.Customer, com.aljumaro.test.proto.CustomerProtos.Customer.Builder, com.aljumaro.test.proto.CustomerProtos.CustomerOrBuilder>(
                  customer_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          customer_ = null;
        }
        return customerBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.aljumaro.test.proto.Customers)
    }

    // @@protoc_insertion_point(class_scope:com.aljumaro.test.proto.Customers)
    private static final com.aljumaro.test.proto.CustomerProtos.Customers DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.aljumaro.test.proto.CustomerProtos.Customers();
    }

    public static com.aljumaro.test.proto.CustomerProtos.Customers getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Customers>
        PARSER = new com.google.protobuf.AbstractParser<Customers>() {
      public Customers parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Customers(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Customers> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Customers> getParserForType() {
      return PARSER;
    }

    public com.aljumaro.test.proto.CustomerProtos.Customers getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aljumaro_test_proto_Customer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aljumaro_test_proto_Customer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_aljumaro_test_proto_Customers_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_aljumaro_test_proto_Customers_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016customer.proto\022\027com.aljumaro.test.prot" +
      "o\"3\n\010Customer\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022" +
      "\r\n\005email\030\003 \001(\t\"@\n\tCustomers\0223\n\010customer\030" +
      "\001 \003(\0132!.com.aljumaro.test.proto.Customer" +
      "B)\n\027com.aljumaro.test.protoB\016CustomerPro" +
      "tosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_aljumaro_test_proto_Customer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_aljumaro_test_proto_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aljumaro_test_proto_Customer_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", });
    internal_static_com_aljumaro_test_proto_Customers_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_aljumaro_test_proto_Customers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_aljumaro_test_proto_Customers_descriptor,
        new java.lang.String[] { "Customer", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
